event_feature_names:

  - image_clu_n
  - image_gsf_ref_eta
  - image_gsf_ref_phi
  - image_gsf_ref_p
  - image_gsf_ref_pt
  - image_gsf_proj_eta
  - image_gsf_proj_phi
  - image_pf_n
  - trk_p
  - trk_pt
  - trk_inp
  - trk_outp
  - trk_dpt
  - trk_eta
  - trk_phi
  - trk_nhits
  - trk_dxy
  - trk_dxy_err
  - trk_dz
  - trk_dz_err
  - gsf_bdtout1
  - gsf_bdtout2
  - gsf_p
  - gsf_pt
  - gsf_eta
  - gsf_phi
  - pfgsf_pt
  - pfgsf_eta
  - pfgsf_phi
  - pfgsf_p
  - pfgsf_inp
  - pfgsf_outp
  - pfgsf_dpt
  - pfgsf_mode_pt
  - pfgsf_mode_eta
  - pfgsf_mode_phi
  - pfgsf_mode_p
  - pfgsf_chi2red
  - pfgsf_dxy
  - pfgsf_dxy_err
  - pfgsf_dz
  - pfgsf_dz_err
  - preid_bdtout1
  - preid_bdtout2
  - eid_rho
  - eid_ele_pt
  - eid_trk_p
  - eid_trk_nhits
  - eid_trk_chi2red
  - eid_gsf_nhits
  - eid_gsf_chi2red
  - eid_sc_E
  - eid_sc_eta
  - eid_sc_etaWidth
  - eid_sc_phiWidth
  - eid_match_seed_dEta
  - eid_match_eclu_EoverP
  - eid_match_SC_EoverP
  - eid_match_SC_dEta
  - eid_match_SC_dPhi
  - eid_shape_full5x5_sigmaIetaIeta
  - eid_shape_full5x5_sigmaIphiIphi
  - eid_shape_full5x5_HoverE
  - eid_shape_full5x5_r9
  - eid_shape_full5x5_circularity
  - eid_brem_frac
  
cluster_feature_names:

  - image_clu_eta
  - image_clu_phi
  - image_clu_e
  - image_clu_nhit

pfcluster_feature_names:

  - image_pf_eta
  - image_pf_phi
  - image_pf_p
  - image_pf_pdgid