global_feature_names:

  - image_clu_n
  - image_pf_n
  - image_gsf_ref_eta
  - image_gsf_ref_phi
  
cluster_feature_names:

  - image_clu_eta
  - image_clu_phi
  - image_clu_e
  - image_clu_nhit

pfcluster_feature_names:

  - image_pf_eta
  - image_pf_phi
  - image_pf_p
  - image_pf_pdgid